# Site settings
title: Freelance web developer
email: milos@gavrilovic.rs
name: Miloš Gavrilović
description: "Freelance web developer"
baseurl: ""
url: "http://milos.gavrilovic.rs"
twitter_username: gavrisimo
github_username:  gavrisimo

# Build settings
markdown: kramdown
permalink: pretty

# Site configuration
paginate: 5
