# Site settings
title:
name:
email:
description:
baseurl: ""
url: "http://milos.gavrilovic.rs"
twitter_username: gavrisimo
github_username:  gavrisimo

# Build settings
markdown: kramdown
permalink: pretty
